/**
 * Navigation utility functions
 * Provides unified page navigation, supporting Swup's no-reload transitions
 */
import { navbarConfig } from "@/config";
import { LinkPresets } from "@constants/link-presets";
import { type NavbarLink } from "@/types/config";
import { pathsEqual } from "./url";


/**
 * Find the parent page that the current path belongs to (e.g. the intermediate page generated by [...menu].astro)
 * @param currentPath The current page's path
 * @returns The page's NavbarLink object if a parent page is found, otherwise undefined
 */
export function getParentLink(currentPath: string): NavbarLink | undefined {
    // Iterate over all links in the navbar
    for (const link of navbarConfig.links) {
        // Check whether there are sub-links and it is not a LinkPreset enum
        if (typeof link !== "number" && link.children && link.children.length > 0) {
            // Check whether the sub-links contain the current path
            for (const child of link.children) {
                let childLink: NavbarLink;
                if (typeof child === "number") {
                    childLink = LinkPresets[child];
                } else {
                    childLink = child;
                }
                // Compare whether the paths match
                if (pathsEqual(childLink.url, currentPath)) {
                    return link;
                }
            }
        }
    }
    return undefined;
}

/**
 * Fallback navigation function
 * Uses a normal page navigation when Swup is unavailable
 */
function fallbackNavigation(
    url: string,
    options?: {
        replace?: boolean;
        force?: boolean;
    },
): void {
    if (typeof window === "undefined") return;
    if (options?.replace) {
        window.location.replace(url);
    } else {
        window.location.href = url;
    }
}

/**
 * Navigate to a given page
 * @param url Target page URL
 * @param options Navigation options
 */
export function navigateToPage(
    url: string,
    options?: {
        replace?: boolean;
        force?: boolean;
    },
): void {
    // Check whether the URL is valid
    if (!url || typeof url !== "string") {
        console.warn("navigateToPage: Invalid URL provided");
        return;
    }

    // If it is an external link, navigate directly
    if (
        url.startsWith("http://") ||
        url.startsWith("https://") ||
        url.startsWith("//")
    ) {
        window.open(url, "_blank");
        return;
    }

    // If it is an anchor link, scroll to the corresponding position
    if (url.startsWith("#")) {
        if (typeof document !== "undefined") {
            const element = document.getElementById(url.slice(1));
            if (element) {
                element.scrollIntoView({ behavior: "smooth" });
            }
        }
        return;
    }

    // Check whether Swup is available
    if (typeof window !== "undefined" && (window as any).swup) {
        try {
            // Use Swup for a no-reload transition
            if (options?.replace) {
                (window as any).swup.navigate(url, { history: false });
            } else {
                (window as any).swup.navigate(url);
            }
        } catch (error) {
            console.error("Swup navigation failed:", error);
            // Fall back to a normal navigation
            fallbackNavigation(url, options);
        }
    } else {
        // Fallback handling when Swup is unavailable
        fallbackNavigation(url, options);
    }
}

/**
 * Get the current page path
 */
export function getCurrentPath(): string {
    return typeof window !== "undefined" ? window.location.pathname : "";
}

/**
 * Check whether this is the home page
 */
export function isHomePage(): boolean {
    const path = getCurrentPath();
    return path === "/" || path === "";
}